# Generated by Django 3.0.7 on 2022-08-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Linea Pedido', 'verbose_name_plural': 'Lineas Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidoss'},
        ),
    ]
