# Generated by Django 3.0.7 on 2020-07-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='comentario',
            new_name='contenido',
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default=2400, upload_to=''),
            preserve_default=False,
        ),
    ]
